
export const types = {
    GET_PRODUCT_ACTION: "GET_PRODUCT_ACTION",
    DELETE_PRODUCT_ACTION: "DELETE_PRODUCT_ACTION",
    INCREASE_COUNT_ACTION: "INCREASE_COUNT_ACTION",
    GET_TOTALSUMM_ACTION: "GET_TOTALSUMM_ACTION",
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    HITS_PRODUCT: 'HITS_PRODUCT',
}