
export const types = {
    GET_PRODUCT_ACTION: "GET_PRODUCT_ACTION",
    DELETE_PRODUCT_ACTION: "DELETE_PRODUCT_ACTION",
    INCREASE_COUNT_ACTION: "INCREASE_COUNT_ACTION",
    GET_TOTALSUMM_ACTION: "GET_TOTALSUMM_ACTION",
    ADD_PRODUCT_INTO_BASKET: 'ADD_PRODUCT_INTO_BASKET',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    HITS_PRODUCT: 'HITS_PRODUCT',
    ADD_TO: "ADD_TO",
    REMOVE_TO: "REMOVE_TO"

}