export const data = [
    {
        id: 1,
        name: 'Смартфон Samsung Galaxy A52 5G 128 Гб EU',
        count: 1,
        price: 45000,
        totalPrice: 45000,
    },
    {
        id: 2,
        name: 'Чехол для Samsung Galaxy A52',
        count: 1,
        price: 500,
        totalPrice: 500,
    },
    {
        id: 2,
        name: 'Чехол для Samsung Galaxy A52',
        count: 1,
        price: 500,
        totalPrice: 500,
    },
    {
        id: 2,
        name: 'Чехол для Samsung Galaxy A52',
        count: 1,
        price: 500,
        totalPrice: 500,
    },
    {
        id: 2,
        name: 'Чехол для Samsung Galaxy A52',
        count: 1,
        price: 500,
        totalPrice: 500,
    },
    {
        id: 2,
        name: 'Чехол для Samsung Galaxy A52',
        count: 1,
        price: 500,
        totalPrice: 500,
    },
    {
        id: 2,
        name: 'Чехол для Samsung Galaxy A52',
        count: 1,
        price: 500,
        totalPrice: 500,
    },
    {
        id: 2,
        name: 'Чехол для Samsung Galaxy A52',
        count: 1,
        price: 500,
        totalPrice: 500,
    },
]
